version: "3.9"
services:
  api:
    container_name: api
    image: rojas901/proyecto-api:v5
    ports:
      - "4000:4000"
    networks:
      - proyectos-net
  
  microservicio1:
    container_name: microservicio1
    image: rojas901/proyecto-microservicio:v6
    ports:
      - "4001"
    networks:
      - proyectos-net
    environment:
      HOST: microservicio1 
  
  microservicio2:
    container_name: microservicio2
    image: rojas901/proyecto-microservicio:v6
    ports:
      - "4001"
    networks:
      - proyectos-net
    environment:
      HOST: microservicio2 

  microservicio3:
    container_name: microservicio3
    image: rojas901/proyecto-microservicio:v6
    ports:
      - "4001"
    networks:
      - proyectos-net
    environment:
      HOST: microservicio3 

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - microservicio1
      - microservicio2
      - microservicio3
    ports:
      - "6027:80"
    networks:
      - proyectos-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  proyectos-net:

#docker compose up (crea todo los especificado en este archivo, si se le agrega -d dice si es done)
#docker compose down (elimina los container creados con el primer comando)
#docker compose build (compila imagenes si hay que hacerlo)
#docker compose logs -f
#build: context: . (toma el dockerfile de directorio raiz)
