version: "3.9"
services:
  api:
    image: rojas901/proyectos-api
    ports:
      - "4000:4000"
    networks:
      - proyectos-app

networks:
  proyectos-app:

#docker compose up (crea todo los especificado en este archivo)
#docker compose down (elimina los container creados con el primer comando)